### ISSUE TITLE
Add option for single stepper to print the register files values

### ISSUE THREAD

**Issue by powerjg** [jlpteaching/dinocpu#23]
We could have another command say "p" to dump the current state of the register file.

In fact, this could be significantly expanded to print anything in the CPU. This should "just work" in theory.

**Comment by microhertz** [comment]
@powerjg I'll take ownership of this issue. I can expand on it to add ability to expose more CPU state.

**Comment by powerjg** [comment]
Sounds great!

**Comment by powerjg** [comment]
You might want to dig into Treadle a little more before going too far down this rat hole. For instance, there's a recent commit that hints there's a REPL in Treadle already: https://github.com/freechipsproject/treadle/commit/e56193a21351b4f083dbd644d2405b6bf5f8a925

**Comment by powerjg** [comment]
Related to #64 and #62
