### ISSUE TITLE
Add csr instructions

### ISSUE THREAD

**Issue by powerjg** [jlpteaching/dinocpu#34]
For the class, we ignored the following instructions. If we added them, it would increase the number of workloads we could run and make it easier to use GCC to compile.

- [x] csrw 
- [x] csrrs 
- [x] csrrc 
- [x] csrrwi
- [x] csrrsi 
- [x] csrrci 

We might be able to get away with adding a "CSR Unit" to hide most of this complexity.
Now that I'm thinking about it, we might be able to do this for the class version, too!

**Comment by nganjehloo** [comment]
I will take care of this :)

**Comment by nganjehloo** [comment]
I think I finished this. CSR instructions all work
