### ISSUE TITLE
Lab1 Tests: Split out add0 into its own test

### ISSUE THREAD

**Issue by powerjg** [jlpteaching/dinocpu#7]
Next time, add0 should be its own test so you can get credit for the rest of the tests passing even if you don't deal with the zero register correctly.

**Comment by DanG100** [comment]
For clarification, does this mean that in the gradescope config for lab 1, the all R-type tests should not include add0, and instead add0 should be its own test.

**Comment by powerjg** [comment]
Yes, I believe so. Though it's been a few months now ;).

IIRC, people were annoyed that they lost 10% of the points for one test failing.

It would actually be *best* if we could somehow make it so each individual test ran on its own, but I'm not sure the best way to do that with the gradescope java library.

**Comment by powerjg** [comment]
Done?
