### ISSUE TITLE
Create hierarchy in classes

### ISSUE THREAD

**Issue by powerjg** [jlpteaching/dinocpu#86]
We now have a lot of different classes and they are all in the dinocpu namespace!

We should take some constants, etc. (e.g., for the CSRs) and put them in their own namespace. We could also probably make a namespace for the memory interfaces.

**Comment by jardhu** [comment]
Seeing that #94 was included as part of the 2020 WQ milestone, I also included this one there as well.

**Comment by deyahruhd** [comment]
Closed by #95.

**Comment by jardhu** [comment]
Closed by #95.
