### ISSUE TITLE
Move pipeline code to dinocpu.pipelined package

### ISSUE THREAD

**Issue by jardhu** [jlpteaching/dinocpu#94]
This should be simple to tackle - to close #86 and help make the dinocpu namespace cleaner, the pipelined CPU models and stage register should all go into a `dinocpu.pipelined` package.

**Comment by jardhu** [comment]
Closed by #95.

**Comment by jardhu** [comment]
@powerjg, Looks like I need to do one more thing to close this issue. Since I moved the tester classes to `dinocpu.test`, all of the test commands in sbt must now utilize `dinocpu.test` instead of `dinocpu`: for example, `testOnly dinocpu.test.PipelinedCPUTester -- -z jal`. The documentation wasn't updated with this in mind since I forgot this would be an issue.

I'll create a new patch in a bit to update the docs.

**Comment by powerjg** [comment]
Great, thanks!

**Comment by jardhu** [comment]
Closed by #97. We could perhaps do some looking into a way to automatically alias the classes in `dinocpu.test` so that they can be run with `testOnly dinocpu.XXXXX`.
